
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Download, Award, Calendar } from 'lucide-react';
import jsPDF from 'jspdf';
import { toast } from '@/components/ui/sonner';

const CertificateGenerator = () => {
  const [formData, setFormData] = useState({
    officiantName: '',
    partner1Name: '',
    partner2Name: '',
    ceremonyDate: '',
    ceremonyLocation: '',
    state: '',
    certificateType: 'marriage'
  });

  const generateCertificate = () => {
    if (!formData.officiantName || !formData.partner1Name || !formData.partner2Name) {
      toast('Please fill in all required fields');
      return;
    }

    try {
      const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4'
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Border
      pdf.setLineWidth(3);
      pdf.setDrawColor(212, 175, 55); // Gold color
      pdf.rect(10, 10, pageWidth - 20, pageHeight - 20);

      // Inner border
      pdf.setLineWidth(1);
      pdf.rect(15, 15, pageWidth - 30, pageHeight - 30);

      // Title
      pdf.setFontSize(24);
      pdf.setFont(undefined, 'bold');
      pdf.setTextColor(139, 69, 19); // Brown color
      const title = formData.certificateType === 'marriage' ? 'MARRIAGE CERTIFICATE' : 'OFFICIANT CERTIFICATE';
      const titleWidth = pdf.getTextWidth(title);
      pdf.text(title, (pageWidth - titleWidth) / 2, 40);

      // Decorative line
      pdf.setLineWidth(2);
      pdf.setDrawColor(212, 175, 55);
      pdf.line(40, 50, pageWidth - 40, 50);

      if (formData.certificateType === 'marriage') {
        // Marriage certificate content
        pdf.setFontSize(14);
        pdf.setFont(undefined, 'normal');
        pdf.setTextColor(0, 0, 0);
        
        let yPos = 70;
        pdf.text('This is to certify that', 40, yPos);
        
        yPos += 20;
        pdf.setFont(undefined, 'bold');
        pdf.setFontSize(18);
        const coupleText = `${formData.partner1Name} and ${formData.partner2Name}`;
        const coupleWidth = pdf.getTextWidth(coupleText);
        pdf.text(coupleText, (pageWidth - coupleWidth) / 2, yPos);
        
        yPos += 20;
        pdf.setFont(undefined, 'normal');
        pdf.setFontSize(14);
        pdf.text('were united in holy matrimony', 40, yPos);
        
        if (formData.ceremonyDate) {
          yPos += 15;
          pdf.text(`on ${new Date(formData.ceremonyDate).toLocaleDateString()}`, 40, yPos);
        }
        
        if (formData.ceremonyLocation) {
          yPos += 15;
          pdf.text(`at ${formData.ceremonyLocation}`, 40, yPos);
        }
        
        yPos += 25;
        pdf.text(`Officiant: ${formData.officiantName}`, 40, yPos);
        
        if (formData.state) {
          yPos += 15;
          pdf.text(`State: ${formData.state}`, 40, yPos);
        }
      } else {
        // Officiant certificate content
        pdf.setFontSize(14);
        pdf.setFont(undefined, 'normal');
        pdf.setTextColor(0, 0, 0);
        
        let yPos = 70;
        pdf.text('This is to certify that', 40, yPos);
        
        yPos += 20;
        pdf.setFont(undefined, 'bold');
        pdf.setFontSize(18);
        const nameWidth = pdf.getTextWidth(formData.officiantName);
        pdf.text(formData.officiantName, (pageWidth - nameWidth) / 2, yPos);
        
        yPos += 20;
        pdf.setFont(undefined, 'normal');
        pdf.setFontSize(14);
        pdf.text('is hereby authorized to perform marriage ceremonies', 40, yPos);
        
        if (formData.state) {
          yPos += 15;
          pdf.text(`in the state of ${formData.state}`, 40, yPos);
        }
        
        yPos += 15;
        pdf.text(`Certificate issued on: ${new Date().toLocaleDateString()}`, 40, yPos);
      }

      // Footer
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'italic');
      pdf.text('Generated by WeddingOfficiantBot - EverUnity Church', 40, pageHeight - 25);

      // Save the PDF
      const filename = formData.certificateType === 'marriage' 
        ? `marriage_certificate_${formData.partner1Name}_${formData.partner2Name}.pdf`
        : `officiant_certificate_${formData.officiantName}.pdf`;
      
      pdf.save(filename);
      toast('Certificate generated successfully!');
    } catch (error) {
      console.error('Certificate generation error:', error);
      toast('Error generating certificate. Please try again.');
    }
  };

  return (
    <Card className="max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Award className="h-5 w-5" />
          Certificate Generator
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label>Certificate Type</Label>
          <Select 
            value={formData.certificateType} 
            onValueChange={(value) => setFormData(prev => ({ ...prev, certificateType: value }))}
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="marriage">Marriage Certificate</SelectItem>
              <SelectItem value="officiant">Officiant Certificate</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label>Officiant Name *</Label>
          <Input
            value={formData.officiantName}
            onChange={(e) => setFormData(prev => ({ ...prev, officiantName: e.target.value }))}
            placeholder="Enter officiant name"
          />
        </div>

        {formData.certificateType === 'marriage' && (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Partner 1 Name *</Label>
                <Input
                  value={formData.partner1Name}
                  onChange={(e) => setFormData(prev => ({ ...prev, partner1Name: e.target.value }))}
                  placeholder="First partner name"
                />
              </div>
              <div className="space-y-2">
                <Label>Partner 2 Name *</Label>
                <Input
                  value={formData.partner2Name}
                  onChange={(e) => setFormData(prev => ({ ...prev, partner2Name: e.target.value }))}
                  placeholder="Second partner name"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label>Ceremony Date</Label>
              <Input
                type="date"
                value={formData.ceremonyDate}
                onChange={(e) => setFormData(prev => ({ ...prev, ceremonyDate: e.target.value }))}
              />
            </div>

            <div className="space-y-2">
              <Label>Ceremony Location</Label>
              <Input
                value={formData.ceremonyLocation}
                onChange={(e) => setFormData(prev => ({ ...prev, ceremonyLocation: e.target.value }))}
                placeholder="Enter ceremony location"
              />
            </div>
          </>
        )}

        <div className="space-y-2">
          <Label>State</Label>
          <Input
            value={formData.state}
            onChange={(e) => setFormData(prev => ({ ...prev, state: e.target.value }))}
            placeholder="Enter state"
          />
        </div>

        <Button onClick={generateCertificate} className="w-full" size="lg">
          <Download className="h-4 w-4 mr-2" />
          Generate Certificate PDF
        </Button>
      </CardContent>
    </Card>
  );
};

export default CertificateGenerator;
