
import { scriptVariations } from './scriptVariations';

interface ScriptData {
  partner1: string;
  partner2: string;
  state?: string;
  personalNotes?: string;
  ceremonyType?: string;
  variationId?: string;
}

const scriptTemplates = {
  'traditional-formal': (data: ScriptData) => `SACRED MARRIAGE CEREMONY SCRIPT

Officiant: "Dearly beloved, we are gathered here today in the sight of God and these witnesses to join ${data.partner1 || '[Partner 1]'} and ${data.partner2 || '[Partner 2]'} in the sacred bond of holy matrimony.

Marriage is an institution ordained by God, signifying the mystical union between Christ and His Church. It is not to be entered into lightly, but reverently, discreetly, advisedly, and in the fear of God.

SCRIPTURE READING
'Love is patient, love is kind. It does not envy, it does not boast, it is not proud...' - 1 Corinthians 13:4-7

DECLARATION OF INTENT
${data.partner1 || '[Partner 1]'}, will you take ${data.partner2 || '[Partner 2]'} to be your wedded spouse, to live together after God's ordinance in the holy estate of matrimony? Will you love, honor, comfort, and keep in sickness and in health, forsaking all others, so long as you both shall live?

[Response: "I will"]

EXCHANGE OF VOWS
${data.partner1 || '[Partner 1]'}, repeat after me: "I, ${data.partner1 || '[Partner 1]'}, take you, ${data.partner2 || '[Partner 2]'}, to be my wedded spouse, to have and to hold from this day forward, for better, for worse, for richer, for poorer, in sickness and in health, to love and to cherish, till death do us part, according to God's holy ordinance."

RING EXCHANGE
These rings are blessed symbols of your unending love. As you place them upon each other's hands, remember that love is eternal, and these circles represent your everlasting commitment.

PRONOUNCEMENT
By the authority vested in me by God and the state of ${data.state || '[STATE]'}, I now pronounce you husband and wife. What God has joined together, let no one separate. You may kiss your spouse.

${data.personalNotes ? `\nPersonal Notes for Wedding Officiant:\n${data.personalNotes}` : ''}

---
Generated by CeremonyPro - Professional Wedding Officiant Toolkit`,

  'secular-casual': (data: ScriptData) => `CELEBRATION OF LOVE CEREMONY

Welcome, everyone! We're here today to celebrate something pretty amazing - the love between ${data.partner1 || '[Partner 1]'} and ${data.partner2 || '[Partner 2]'}.

Love isn't just about finding the perfect person - it's about seeing an imperfect person perfectly. Today, these two are making a promise to see each other exactly that way, every single day.

WHAT MARRIAGE MEANS
Marriage is about partnership, friendship, and choosing each other again and again. It's about building a life together filled with shared dreams, inside jokes, and the kind of love that grows stronger with time.

PERSONAL VOWS
${data.partner1 || '[Partner 1]'} and ${data.partner2 || '[Partner 2]'}, you've written your own promises to each other. These aren't just words - they're the foundation of your future together.

[Personal vows exchanged]

RING CEREMONY
These rings represent your commitment - not just for today, but for all the days to come. The good days, the challenging days, and all the ordinary, beautiful days in between.

${data.partner1 || '[Partner 1]'}, as you place this ring on ${data.partner2 || '[Partner 2]'}'s finger, say: "With this ring, I choose you, today and always."

CELEBRATION
By the power of your love and the commitment you've made today, and by the authority vested in me by the state of ${data.state || '[STATE]'}, I'm thrilled to pronounce you married! 

Now kiss and let's celebrate!

${data.personalNotes ? `\nWedding Officiant Notes:\n${data.personalNotes}` : ''}

---
Created with CeremonyPro - Your Professional Marriage Ceremony Partner`,

  'lgbtq-celebration': (data: ScriptData) => `CELEBRATION OF LOVE & EQUALITY

Friends and family, today we gather to witness and celebrate the beautiful union of ${data.partner1 || '[Partner 1]'} and ${data.partner2 || '[Partner 2]'} - a testament to love's triumph and the power of authentic connection.

Love is love. It transcends boundaries, defies convention, and creates its own beautiful truth. Today, we honor not just this couple's love, but the courage it takes to live authentically and love boldly.

THE JOURNEY TO TODAY
${data.partner1 || '[Partner 1]'} and ${data.partner2 || '[Partner 2]'}, your love story is unique and beautiful. You've chosen to be vulnerable with each other, to build a life together, and to stand proudly in your truth.

AFFIRMATION OF LOVE
Do you, ${data.partner1 || '[Partner 1]'}, promise to love ${data.partner2 || '[Partner 2]'} with authenticity, to support their dreams, to celebrate their identity, and to build a life filled with joy, equality, and endless love?

[Response: "I do"]

EXCHANGE OF PROMISES
These rings symbolize your eternal bond - a love that is proud, strong, and unbreakable. May they remind you daily of this moment and the beautiful life you're creating together.

PRONOUNCEMENT OF MARRIAGE
With great joy and by the authority vested in me by the state of ${data.state || '[STATE]'}, I now pronounce you married! Your love wins today and always.

You may kiss your spouse!

${data.personalNotes ? `\nOfficiant's Personal Notes:\n${data.personalNotes}` : ''}

---
Crafted with CeremonyPro - Inclusive Wedding Ceremony Solutions`
};

export const generateEnhancedScript = (data: ScriptData): string => {
  const template = scriptTemplates[data.variationId as keyof typeof scriptTemplates];
  if (template) {
    return template(data);
  }
  
  // Fallback to original template
  return generateOriginalTemplate(data);
};

const generateOriginalTemplate = (data: ScriptData): string => {
  const { partner1, partner2, state, personalNotes } = data;
  
  return `PROFESSIONAL WEDDING CEREMONY SCRIPT

Officiant: "Welcome, family and friends. We are gathered here today to witness and celebrate the sacred union of ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'} in holy matrimony.

Marriage is a sacred bond, a commitment to love, honor, and cherish one another through all of life's joys and challenges. Today, we celebrate not just the love between ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}, but the commitment they make to build a life together.

OPENING REMARKS

${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}, you have chosen to share your lives together in marriage. Today, in the presence of your loved ones, you make this sacred commitment official before God and the state.

DECLARATION OF INTENT

Do you, ${partner1 || '[Partner 1]'}, take ${partner2 || '[Partner 2]'} to be your lawfully wedded spouse, to have and to hold, in sickness and in health, for richer or poorer, for better or worse, for as long as you both shall live?

[Response: "I do"]

Do you, ${partner2 || '[Partner 2]'}, take ${partner1 || '[Partner 1]'} to be your lawfully wedded spouse, to have and to hold, in sickness and in health, for richer or poorer, for better or worse, for as long as you both shall live?

[Response: "I do"]

EXCHANGE OF WEDDING RINGS

The wedding ring is a symbol of eternity, with no beginning and no end. May these rings remind you always of the sacred vows you have taken today and the covenant of marriage you now enter.

${partner1 || '[Partner 1]'}, place the ring on ${partner2 || '[Partner 2]'}'s finger and repeat after me: "With this ring, I thee wed, and pledge my faithful love."

${partner2 || '[Partner 2]'}, place the ring on ${partner1 || '[Partner 1]'}'s finger and repeat after me: "With this ring, I thee wed, and pledge my faithful love."

PRONOUNCEMENT OF MARRIAGE

By the power vested in me as a wedding officiant by the state of ${state || '[STATE]'}, and according to the laws governing marriage in this jurisdiction, I now pronounce you husband and wife. You may kiss your bride/groom!

PRESENTATION

Ladies and gentlemen, it is my honor to present to you for the first time as a married couple, ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}!

${personalNotes ? `\nPersonal Notes for Officiant:\n${personalNotes}` : ''}

---
This wedding ceremony script was generated by CeremonyPro - Professional Wedding Officiant Toolkit`;
};

export { generateOriginalTemplate as generateScriptTemplate };
