
interface ScriptData {
  partner1: string;
  partner2: string;
  state?: string;
  personalNotes?: string;
  ceremonyType?: string;
}

export const generateScriptTemplate = (data: ScriptData): string => {
  const { partner1, partner2, state, personalNotes } = data;
  
  return `PROFESSIONAL WEDDING CEREMONY SCRIPT

Officiant: "Welcome, family and friends. We are gathered here today to witness and celebrate the sacred union of ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'} in holy matrimony.

Marriage is a sacred bond, a commitment to love, honor, and cherish one another through all of life's joys and challenges. Today, we celebrate not just the love between ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}, but the commitment they make to build a life together.

OPENING REMARKS

${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}, you have chosen to share your lives together in marriage. Today, in the presence of your loved ones, you make this sacred commitment official before God and the state.

DECLARATION OF INTENT

Do you, ${partner1 || '[Partner 1]'}, take ${partner2 || '[Partner 2]'} to be your lawfully wedded spouse, to have and to hold, in sickness and in health, for richer or poorer, for better or worse, for as long as you both shall live?

[Response: "I do"]

Do you, ${partner2 || '[Partner 2]'}, take ${partner1 || '[Partner 1]'} to be your lawfully wedded spouse, to have and to hold, in sickness and in health, for richer or poorer, for better or worse, for as long as you both shall live?

[Response: "I do"]

EXCHANGE OF WEDDING RINGS

The wedding ring is a symbol of eternity, with no beginning and no end. May these rings remind you always of the sacred vows you have taken today and the covenant of marriage you now enter.

${partner1 || '[Partner 1]'}, place the ring on ${partner2 || '[Partner 2]'}'s finger and repeat after me: "With this ring, I thee wed, and pledge my faithful love."

${partner2 || '[Partner 2]'}, place the ring on ${partner1 || '[Partner 1]'}'s finger and repeat after me: "With this ring, I thee wed, and pledge my faithful love."

PRONOUNCEMENT OF MARRIAGE

By the power vested in me as a wedding officiant by the state of ${state || '[STATE]'}, and according to the laws governing marriage in this jurisdiction, I now pronounce you husband and wife. You may kiss your bride/groom!

PRESENTATION

Ladies and gentlemen, it is my honor to present to you for the first time as a married couple, ${partner1 || '[Partner 1]'} and ${partner2 || '[Partner 2]'}!

${personalNotes ? `\nPersonal Notes for Officiant:\n${personalNotes}` : ''}

---
This wedding ceremony script was generated by CeremonyPro - Professional Wedding Officiant Toolkit`;
};
